[project]
name = "python-utilities"
version = "0.1.0"
description = "A collection of Python utilities"
authors = [
    { name = "Your Name", email = "your.email@example.com" }
]
dependencies = [
    "requests>=2.31.0",
    "keyring>=24.0.0",
    "tqdm>=4.66.0",
]
requires-python = ">=3.8"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/python_utilities"] 